### ISSUE TITLE
[Browser][Bug] UMD build errors in browser

### ISSUE THREAD

**Issue by woutervh-** [jerairrest/react-chartjs-2#277]
Trying to use the UMD build directly from unpkg:
https://unpkg.com/react-chartjs-2@2.7.0/dist/react-chartjs-2.js

However, it is trying to access `process` (node global) which does not exist in browser.

```
Uncaught ReferenceError: process is not defined
    at react-chartjs-2.js:80
    at react-chartjs-2.js:4
    at react-chartjs-2.js:5
(anonymous) @ react-chartjs-2.js:80
(anonymous) @ react-chartjs-2.js:4
(anonymous) @ react-chartjs-2.js:5
```

**Comment by jerairrest** [comment]
Should be fixed in https://github.com/jerairrest/react-chartjs-2/releases/tag/2.7.4

**Comment by andrewmclagan** [comment]
This is still an issue.

Yarn 2 PnP and also Webpack 5 fails to install or build with this packages as it references `process`, a node global. 

These latest versions of tooling have better dependancy resolution and do not allow access to non existing globals.
